[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "HGCNN"
version = "0.1.0"

[tool.setuptools]
packages = ["data", "model", "model.MoonLabHGNN", "model.QualityHGNN", "utils"]
package-dir = {"" = "src"}

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
norecursedirs = [".git", "venv*"]